# Generated by Django 4.0.3 on 2022-07-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_type', models.CharField(max_length=100)),
                ('date_bought', models.CharField(max_length=100)),
                ('date_listed', models.CharField(max_length=100)),
                ('date_sold', models.CharField(max_length=100)),
                ('price_paid', models.CharField(max_length=100)),
                ('listing_price', models.CharField(max_length=100)),
                ('final_price', models.CharField(max_length=100)),
                ('selling_platform', models.CharField(max_length=100)),
                ('shipping_fee', models.CharField(max_length=100)),
                ('additional_fees', models.CharField(max_length=100)),
                ('total_profit', models.CharField(default='0', max_length=100)),
                ('item_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_uploaded', to='main.user')),
            ],
        ),
    ]
