# Generated by Django 4.0.3 on 2022-08-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_item_final_price_item_gross_profit_and_more'),
        ('main', '0002_supply'),
    ]

    operations = [
    ]
